#!/bin/sh
# $1 = tau, $2 = order, $3 = kappa
BatchRunTwoCirclesLarge 0.1 1 2.0
BatchRunTwoCirclesLarge 0.1 2 2.0
BatchRunTwoCirclesLarge 1.0 1 2.0
BatchRunTwoCirclesLarge 1.0 2 2.0
BatchRunTwoCirclesLarge 10.0 1 2.0
BatchRunTwoCirclesLarge 10.0 2 2.0
BatchRunTwoCirclesLarge 100.0 1 2.0
BatchRunTwoCirclesLarge 100.0 2 2.0
BatchRunTwoCirclesLarge 0.1 1 0.0
BatchRunTwoCirclesLarge 0.1 2 0.0
BatchRunTwoCirclesLarge 1.0 1 0.0
BatchRunTwoCirclesLarge 1.0 2 0.0
BatchRunTwoCirclesLarge 10.0 1 0.0
BatchRunTwoCirclesLarge 10.0 2 0.0
BatchRunTwoCirclesLarge 100.0 1 0.0
BatchRunTwoCirclesLarge 100.0 2 0.0


